# Autogenerated wrapper script for MbedTLS_jll for i686-w64-mingw32
export libmbedcrypto, libmbedtls, libmbedx509

JLLWrappers.@generate_wrapper_header("MbedTLS")
JLLWrappers.@declare_library_product(libmbedcrypto, "libmbedcrypto.dll")
JLLWrappers.@declare_library_product(libmbedtls, "libmbedtls.dll")
JLLWrappers.@declare_library_product(libmbedx509, "libmbedx509.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmbedcrypto,
        "bin\\libmbedcrypto.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmbedtls,
        "bin\\libmbedtls.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmbedx509,
        "bin\\libmbedx509.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
